





module.exports = {
    PORT : process.env.PORT || 3000,
    DB_URL : process.env.DB_URL,
    JWT_SECRET_KEY : process.env.JWT_SECRET_KEY,
    JWT_AUTH_EXPIRE_DAYS : process.env.JWT_AUTH_EXPIRE_DAYS,
    CLOUDINARY_CLOUD_NAME : process.env.CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY : process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET : process.env.CLOUDINARY_API_SECRET,
    CLOUDINARY_FOLDER_NAME : process.env.CLOUDINARY_FOLDER_NAME
}